Repository Juarpla/handcrafted-haven, pull requests merged in 2024-10, with the labels that each got.

#25 Deploy on Vercel
  README.md
Labels: enhancement

#26 Set up linter and formatter
  .eslintrc.json
  .prettierignore
  .prettierrc.json
  next.config.mjs
  package-lock.json
  package.json
Labels: enhancement

#22 added login page with OAuth from Github
  src/app/dashboard/login/page.tsx
  src/app/ui/button.tsx
  src/app/ui/fonts.ts
Labels: enhancement

#41 Product page
  src/app/dashboard/aboutUs.tsx
  src/app/dashboard/page.tsx
  src/app/ui/products/ProductImages.tsx
  src/app/ui/products/page.tsx
  src/components/promotionalProducts.tsx
Labels: enhancement

#39 added login and logout for github OAuth
  nextauth.config.ts
  src/app/dashboard/page.tsx
  src/app/page.tsx
  src/app/ui/Navigation.tsx
  src/app/ui/button.tsx
  src/app/ui/logoutbutton.tsx
  src/pages/api/auth/[...nextauth].ts
Labels: enhancement

#46 ⚙️ Fix next auth connection
  .env.local
  .gitignore
  package-lock.json
  src/app/api/auth/nextauth.ts
Labels: enhancement

#48 Seller bio form
  src/app/sellers/aboutSeller.tsx
  src/app/sellers/page.tsx
Labels: enhancement

#44 added access fix so dashboard cannot be accessed via URL
  src/app/dashboard/page.tsx
  src/app/layout.tsx
Labels: enhancement

#47 add for movil hero image and navigation with logo
  src/app/components/HeroSection.tsx
  src/app/ui/Navigation.tsx
  src/app/ui/logos.webp
Labels: enhancement

#54 Create a footer section component 🦶
  src/app/dashboard/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/ui/homepage/footer-menu.tsx
  src/app/ui/homepage/footer.tsx
  src/app/ui/layout/Navigation.tsx
  src/app/ui/products/page.tsx
Labels: enhancement

#56 Add next auth token config 🔍
  src/app/api/auth/nextauth.ts
Labels: bug

#55 add new
  .eslintrc.json
  README.md
  next.config.mjs
  package-lock.json
  package.json
  src/app/components/Followers.tsx
  src/app/components/HeroSection.tsx
  src/app/components/MyAccountPage.tsx
  src/app/components/SatisfiedClients.tsx
  src/app/components/Settings.tsx
  src/app/dashboard/aboutUs.tsx
  src/app/dashboard/followers/page.tsx
  src/app/dashboard/login/page.tsx
  src/app/dashboard/page.tsx
  src/app/dashboard/settings/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/app/sellers/SellerImages.tsx
  src/app/sellers/aboutSeller.tsx
  src/app/sellers/page.tsx
  src/app/ui/button.tsx
  src/app/ui/fonts.ts
  src/app/ui/logoutbutton.tsx
  src/app/ui/products/ProductImages.tsx
  src/app/ui/products/page.tsx
  src/components/promotionalProducts.tsx
  src/pages/api/auth/[...nextauth].ts
  tailwind.config.ts
  tsconfig.json
Labels: enhancement

#57 🏄‍♂️ Fix navigation web
  next.config.mjs
  src/app/dashboard/followers/page.tsx
  src/app/dashboard/login/page.tsx
  src/app/dashboard/page.tsx
  src/app/dashboard/settings/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/products/page.tsx
  src/app/sellers/page.tsx
  src/app/ui/dashboard/Followers.tsx
  src/app/ui/dashboard/MyAccountPage.tsx
  src/app/ui/dashboard/Settings.tsx
  src/app/ui/dashboard/aboutUs.tsx
  src/app/ui/home/HeroSection.tsx
  src/app/ui/home/SatisfiedClients.tsx
  src/app/ui/home/promotionalProducts.tsx
  src/app/ui/layout/Navigation.tsx
  src/app/ui/layout/footer-menu.tsx
  src/app/ui/layout/footer.tsx
  src/app/ui/sellers/SellerImages.tsx
  src/app/ui/sellers/aboutSeller.tsx
Labels: bug, enhancement

#60 added add product page form and made the sidenav bar in the dashboard…
  src/app/account/products/page.tsx
  src/app/ui/dashboard/MyAccountPage.tsx
  src/app/ui/dashboard/Settings.tsx
  src/app/ui/dashboard/sidebar.tsx
Labels: enhancement

#64 😈 Fix deploy
  README.md
  pnpm-lock.yaml
  src/app/api/auth/[...nextauth]/routes.ts
  src/app/api/auth/nextauth.ts
  src/app/dashboard/page.tsx
  src/app/ui/dashboard/MyAccountPage.tsx
  src/pages/api/auth/[...nextauth].ts
Labels: bug

#66 🧨 Fix routes and files organization
  src/app/layout.tsx
  src/app/products/[id]/page.tsx
  src/app/ui/products/ProductCard.tsx
  src/fonts/GeistMonoVF.woff
  src/fonts/GeistVF.woff
  src/lib/data.ts
  src/lib/definitions.ts
  src/lib/placeholder-data.ts
  src/lib/utils.ts
  src/seed/route.ts
Labels: bug, invalid

#71 added product review section and updated the dashboard page to includ…
  src/app/account/products/page.tsx
  src/app/product/[id]/page.tsx
  src/app/ui/dashboard/Followers.tsx
  src/app/ui/dashboard/sidebar.tsx
Labels: enhancement

#72 nav bar profile
  src/app/ui/dashboard/MyAccountPage.tsx
  src/app/ui/layout/Navigation.tsx
Labels: bug

#73 Add viewer comments flow in products
  .gitignore
  next.config.mjs
  src/app/product/[id]/page.tsx
  src/app/products/[id]/page.tsx
  src/app/ui/products/AddReview.tsx
  src/app/ui/products/CommentList.tsx
  src/app/ui/products/ProductCard.tsx
  src/app/ui/products/ProductDetails.tsx
  src/app/ui/products/ProductImages.tsx
  src/app/ui/products/StarRating.tsx
  src/lib/actions.ts
  src/lib/data.ts
  src/lib/definitions.ts
  src/lib/placeholder-data.ts
  src/lib/utils.ts
  src/seed/route.ts
Labels: bug, enhancement

#76 add searchbar
  next.config.mjs
  src/app/account/products/page.tsx
  src/app/ui/dashboard/MyAccountPage.tsx
  src/app/ui/dashboard/sidebar.tsx
  src/app/ui/layout/Navigation.tsx
  src/app/ui/products/ProductImages.tsx
  src/app/ui/products/SearchBar.tsx
  src/lib/actions.ts
Labels: enhancement

#77 Form styling
  pnpm-lock.yaml
  src/app/ui/sellers/aboutSeller.tsx
Labels: enhancement

#78 add style movil
  pnpm-lock.yaml
  src/app/account/products/page.tsx
  src/app/products/page.tsx
  src/app/sellers/page.tsx
  src/app/ui/dashboard/MyAccountPage.tsx
  src/app/ui/dashboard/Settings.tsx
  src/app/ui/dashboard/sidebar.tsx
  src/app/ui/layout/Navigation.tsx
  src/app/ui/products/SearchBar.tsx
  src/app/ui/sellers/SellerImages.tsx
  src/app/ui/sellers/aboutSeller.tsx
Labels: bug

#74 added list sort
  src/app/ui/products/ProductCard.tsx
  src/app/ui/products/ProductImages.tsx
  src/app/ui/products/ProductSort.tsx
  tailwind.config.ts
Labels: enhancement
